//
//  RecurrenceParityTests.swift
//  cueTests
//
//  THE GATE (full-calendar-replica-sync Phase 0). Replays the golden parity-fixture
//  corpus generated by the backend engine (cue-api
//  recurrence-parity-fixtures.spec.ts → docs/fixtures/recurrence-parity.json,
//  vendored to cueTests/Fixtures via Scripts/sync-recurrence-fixtures.sh) and asserts
//  the Swift `RecurrenceEngine` reproduces every occurrence to epoch-millisecond
//  exactness. Any divergence — a DST edge, a selector, a month-overflow — fails here
//  rather than shipping a wrong calendar. Refresh the corpus in lock-step whenever
//  either engine changes.
//

import Foundation
import Testing
@testable import cue

// MARK: - Fixture wire model

private struct ParityFixture: Codable, Sendable, CustomStringConvertible {
    let name: String
    let task: FixtureTask
    let config: RecurrenceConfig
    let exceptions: [FixtureException]
    let window: FixtureWindow
    let expected: [FixtureExpected]

    var description: String { name }
}

private struct FixtureTask: Codable, Sendable {
    let id: String
    let title: String
    let timezone: String
    let startAt: Date?
    let endAt: Date?
    let isAllDay: Bool
}

private struct FixtureException: Codable, Sendable {
    let originalStartAt: Date
    let isSkipped: Bool
    let overrideStartAt: Date?
    let overrideEndAt: Date?
    let overrideTitle: String?
    let completedAt: Date?
}

private struct FixtureWindow: Codable, Sendable {
    let from: Date
    let to: Date
}

private struct FixtureExpected: Codable, Sendable {
    let originalStart: Date?
    let occurrenceStart: Date?
    let occurrenceEnd: Date?
    let title: String
    let completedAt: Date?
    let isException: Bool
}

// MARK: - Corpus loader

/// Marker class so `Bundle(for:)` resolves the test bundle.
private final class ParityBundleMarker {}

private enum ParityCorpus {
    /// Loads the vendored corpus. Tries the test bundle first (if the synchronized
    /// group copied the JSON as a resource), then falls back to the on-disk vendored
    /// path derived from `#filePath` — so the suite is green on local dev regardless
    /// of how the resource is bundled.
    static func load() throws -> [ParityFixture] {
        let data = try loadData()
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .custom { decoder in
            let container = try decoder.singleValueContainer()
            let raw = try container.decode(String.self)

            guard let date = isoDate(from: raw) else {
                throw DecodingError.dataCorruptedError(
                    in: container,
                    debugDescription: "Unparseable ISO-8601 date: \(raw)"
                )
            }

            return date
        }

        return try decoder.decode([ParityFixture].self, from: data)
    }

    private static func loadData() throws -> Data {
        if let url = Bundle(for: ParityBundleMarker.self)
            .url(forResource: "recurrence-parity", withExtension: "json") {
            return try Data(contentsOf: url)
        }

        // Fallback: <repo>/cueTests/Fixtures/recurrence-parity.json, from this file's
        // path (cueTests/Unit/RecurrenceParityTests.swift → up two → cueTests/).
        let thisFile = URL(fileURLWithPath: #filePath)
        let cueTestsDir = thisFile.deletingLastPathComponent().deletingLastPathComponent()
        let fixture = cueTestsDir
            .appendingPathComponent("Fixtures/recurrence-parity.json")

        return try Data(contentsOf: fixture)
    }

    private static func isoDate(from raw: String) -> Date? {
        let withFraction = ISO8601DateFormatter()
        withFraction.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        if let date = withFraction.date(from: raw) { return date }

        let plain = ISO8601DateFormatter()
        plain.formatOptions = [.withInternetDateTime]

        return plain.date(from: raw)
    }
}

/// Loaded once, synchronously, for the parameterized test's `arguments`. A load
/// failure surfaces as an empty argument set — caught by `corpusIsLoaded`.
private let parityFixtures: [ParityFixture] = (try? ParityCorpus.load()) ?? []

// MARK: - Suite

struct RecurrenceParityTests {

    @Test("parity corpus loads and is non-trivial")
    func corpusIsLoaded() {
        #expect(parityFixtures.count >= 50, "expected the full vendored corpus")
    }

    @Test("Swift engine matches the backend oracle", arguments: parityFixtures)
    fileprivate func matchesOracle(_ fixture: ParityFixture) throws {
        let start = try #require(fixture.task.startAt, "\(fixture.name): missing startAt")
        let timeZone = try #require(
            TimeZone(identifier: fixture.task.timezone),
            "\(fixture.name): bad timezone \(fixture.task.timezone)"
        )

        let exceptions = fixture.exceptions.map {
            RecurrenceException(
                originalStartAt: $0.originalStartAt,
                isSkipped: $0.isSkipped,
                overrideStartAt: $0.overrideStartAt,
                overrideEndAt: $0.overrideEndAt,
                overrideTitle: $0.overrideTitle,
                completedAt: $0.completedAt
            )
        }

        let produced = RecurrenceEngine.expandOccurrences(
            anchorStart: start,
            anchorEnd: fixture.task.endAt,
            title: fixture.task.title,
            timeZone: timeZone,
            config: fixture.config,
            exceptions: exceptions,
            windowFrom: fixture.window.from,
            windowTo: fixture.window.to
        )

        #expect(
            produced.count == fixture.expected.count,
            "\(fixture.name): occurrence count \(produced.count) != expected \(fixture.expected.count)"
        )

        for (index, expected) in fixture.expected.enumerated() {
            guard index < produced.count else { break }

            let actual = produced[index]
            let label = "\(fixture.name)[\(index)]"

            #expect(
                sameInstant(actual.originalStart, expected.originalStart),
                "\(label): originalStart \(actual.originalStart) != \(String(describing: expected.originalStart))"
            )
            #expect(
                sameInstant(actual.occurrenceStart, expected.occurrenceStart),
                "\(label): occurrenceStart \(actual.occurrenceStart) != \(String(describing: expected.occurrenceStart))"
            )
            #expect(
                sameInstant(actual.occurrenceEnd, expected.occurrenceEnd),
                "\(label): occurrenceEnd \(String(describing: actual.occurrenceEnd)) != \(String(describing: expected.occurrenceEnd))"
            )
            #expect(actual.title == expected.title, "\(label): title")
            #expect(
                sameInstant(actual.completedAt, expected.completedAt),
                "\(label): completedAt"
            )
            #expect(actual.isException == expected.isException, "\(label): isException")
        }
    }

    /// Epoch-millisecond equality (absorbs sub-ms float noise), nil-safe.
    private func sameInstant(_ lhs: Date?, _ rhs: Date?) -> Bool {
        switch (lhs, rhs) {
        case (nil, nil):
            return true
        case let (left?, right?):
            let leftMillis = Int64((left.timeIntervalSince1970 * 1000).rounded())
            let rightMillis = Int64((right.timeIntervalSince1970 * 1000).rounded())

            return leftMillis == rightMillis
        default:
            return false
        }
    }
}
